name: Add Label

on:
  issues:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: label a_definir
        uses: actions-ecosystem/action-add-labels@v1
        if: join(github.event.issue.labels) == ''
        with:
          labels: a_definir
      
      - name: label CCRAS
        uses: actions-ecosystem/action-add-labels@v1
        if: contains(${{ github.event.issue.body }}, CCRAS)
        with:
          labels: CCRAS
      
      - name: label v1.3.2
        uses: actions-ecosystem/action-add-labels@v1
        if: contains(${{ github.event.issue.body }}, 1.3.2)
        with:
          labels: v1.3.2
                
      - name: label v1.3.3
        uses: actions-ecosystem/action-add-labels@v1
        if: contains(${{ github.event.issue.body }}, 1.3.3)
        with:
          labels: v1.3.3
