name: Add Label

on:
  issues:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: label a_definir
        if: join(github.event.issue.labels) == ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: a_definir
       
      - name: label bug
        if: contains(github.event.issue.body, 'bug') || contains(github.event.issue.body, 'Bug') || contains(github.event.issue.body, 'BUG') || contains(github.event.issue.title, 'bug') || contains(github.event.issue.title, 'Bug') || contains(github.event.issue.title, 'BUG')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: bug
      
      - name: label CCRAS
        if: contains(github.event.issue.body, 'CCRAS')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: CCRAS
      
      - name: label v1.3.2
        if: contains(github.event.issue.body, '1.3.2')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: v1.3.2
                
      - name: label v1.3.3
        if: contains(github.event.issue.body, '1.3.3')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: v1.3.3
                          
      - name: label v1.4.0
        if: contains(github.event.issue.body, '1.4.0')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: v1.4.0
