name: Add Label

on:
  issues:
    types: opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: label bug
        if: contains(github.event.issue.body, 'bug') || contains(github.event.issue.body, 'Bug') || contains(github.event.issue.body, 'BUG') || contains(github.event.issue.title, 'bug') || contains(github.event.issue.title, 'Bug') || contains(github.event.issue.title, 'BUG')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: bug
          
      - name: label a_definir
        if: join(github.event.issue.labels) == ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: a_definir
      
      # Noms société
      - name: label CCRAS
        if: contains(github.event.issue.body, 'CCRAS')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: CCRAS
      - name: label DOCSIDE
        if: contains(github.event.issue.body, 'DOCSIDE')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: DOCSIDE
                          
      # Versions
      - name: label v1.4.6
        if: contains(github.event.issue.body, '1.4.6')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: v1.4.6                              
      - name: label v1.4.7
        if: contains(github.event.issue.body, '1.4.7')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: v1.4.7
      - name: label v2.0.1
        if: contains(github.event.issue.body, '2.0.1')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: v2.0.1
      - name: label v2.0.2
        if: contains(github.event.issue.body, '2.0.2')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: v2.0.2
      - name: label v2.0.3
        if: contains(github.event.issue.body, '2.0.3')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: v2.0.3
      - name: label v2.2.0
        if: contains(github.event.issue.body, '2.2.0')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: v2.2.0
