name: test

on:
  issues:
    types: opened

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@master
        id: branch
        with:
          msg: ${{ github.event.issue.body }}
          separator: "%0D%0A"
          maxsplit: -1
      - name: View issue information
         run:echo "$branch.length"
